image: node:latest

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mkdir .public
  - mkdir .public/dist
  - cp dist/*.js .public/dist/
  - mv _ENHANCE_THIS.html .public/index.html
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
