image: node:latest

build-job:
  stage: build
  script:
    - npm install
    - npm run build

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
